name: Deploy Database

on:

  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  Deploy:

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build SQL Project
        run: |
          msbuild DatabaseProject\Database.sqlproj /p:Configuration=Release

      - name: Deploy Database
        shell: powershell
        env:
          MASTER_DB_CONNECTION: ${{ secrets.MASTER_DB_CONNECTION }}
        run: |
          .\Scripts\Deploy-AllTenants.ps1
